name: rapido-infrastructure

services:
  rapido.postgres:
    image: postgres
    shm_size: '4gb'
    container_name: postgres
    restart: unless-stopped
    networks:
      - rapido
    environment:
      POSTGRES_PASSWORD: Admin12!
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  rapido.rabbitmq:
    image: "rabbitmq:3.11.7-management"
    container_name: rabbitmq
    restart: unless-stopped
    
    networks:
      - rapido
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
        - "5672:5672"
        - "15672:15672"

  rapido.redis:
    image: redis:7.2
    container_name: redis
    restart: unless-stopped
    networks:
      - rapido
    ports:
      - "6379:6379"
    volumes: 
      - redis:/data

  rapido.consul:
    image: hashicorp/consul:latest
    container_name: consul
    hostname: consul
    networks:
      - rapido
    ports:
      - "8500:8500"
    volumes:
      - consul:/var/lib/consul/data
      - consul:/var/lib/consul/config

  rapido.jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    networks:
      - rapido
    ports: 
      - "4317:4317"
      - "4318:4318"
      - "16686:16686"

  rapido.papercut:
    image: changemakerstudiosus/papercut-smtp:latest
    container_name: papercut
    networks:
      - rapido
    ports:
      - "8080:80"
      - "25:25"
        
  rapido.vault:
    image: hashicorp/vault:latest
    container_name: vault
    networks:
      - rapido
    ports: 
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=secret
    cap_add:
      - IPC_LOCK
        
  rapido.seq:
    image: datalust/seq
    container_name: seq
    networks:
      - rapido
    ports:
      - "5341:5341"
      - "80:80"
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seq:/data
        
  rapido.terraform:
    image: hashicorp/terraform:latest
    container_name: terraform
    working_dir: /terraform
    depends_on:
       - rapido.vault
    networks:
      - rapido
    volumes:
       - ./terraform:/terraform
    environment:
      VAULT_ADDR: "http://rapido.vault:8200"
      VAULT_TOKEN: ${VAULT_TOKEN:-"secret"}
    entrypoint: [ "/bin/sh", "-c" ]
    command: "/terraform/run.sh"
      
networks:
  rapido:
    name: rapido

volumes:
  postgres:
    driver: local

  rabbitmq:
    driver: local

  redis:
    driver: local

  consul:
    driver: local

  jaeger:
    driver: local

  papercut:
    driver: local
    
  vault:
    driver: local
    
  seq:
    driver: local
    
  terraform:
    driver: local