version: "3.9"
name: Rapido

services:
  postgres:
    image: postgres
    shm_size: '4gb'
    container_name: postgres
    restart: unless-stopped
    networks:
      - rapido
    environment:
      POSTGRES_PASSWORD: Admin12!
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  rabbitmq:
    image: "rabbitmq:3.11.7-management"
    container_name: rabbitmq
    restart: unless-stopped
    
    networks:
      - rapido
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
        - 5672:5672
        - 15672:15672

  redis:
    image: redis:7.2
    container_name: redis
    restart: unless-stopped
    networks:
      - rapido
    ports:
      - 6379:6379
    volumes: 
      - redis:/data

  consul:
    image: hashicorp/consul:latest
    container_name: consul
    hostname: consul
    networks:
      - rapido
    ports:
      - "8500:8500"
    volumes:
      - consul:/var/lib/consul/data
      - consul:/var/lib/consul/config

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    networks:
      - rapido
    ports: 
      - 4317:4317
      - 4318:4318
      - 16686:16686

  papercut:
    image: changemakerstudiosus/papercut-smtp:latest
    container_name: papercut
    ports:
      - 8080:80
      - 25:25

networks:
  rapido:
    name: rapido

volumes:
  postgres:
    driver: local

  rabbitmq:
    driver: local

  redis:
    driver: local

  consul:
    driver: local

  jaeger:
    driver: local

  papercut:
    driver: local