name: rapido-services

services:
  rapido.api-gateway:
    build:
      context: ../
      dockerfile: src/APIGateway/Rapido.APIGateway/Dockerfile
    container_name: api-gateway
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ASPNETCORE_HTTP_PORTS: 5000
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://rapido.jaeger:4317"
    ports:
      - 5000:5000
    networks:
      - rapido
        
  rapido.saga:
      build:
        context: ../
        dockerfile: src/Saga/Rapido.Saga/Dockerfile
      container_name: saga
      restart: unless-stopped
      environment:
        ASPNETCORE_ENVIRONMENT: Docker
        ASPNETCORE_HTTP_PORTS: 5100
        OTEL_EXPORTER_OTLP_ENDPOINT: "http://rapido.jaeger:4317"
      ports:
        - 5100
      networks:
        - rapido

  rapido.users:
    build:
      context: ../
      dockerfile: src/Services/Users/Rapido.Services.Users.Api/Dockerfile
    container_name: users-service
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ASPNETCORE_HTTP_PORTS: 5020
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://rapido.jaeger:4317"
    ports:
      - 5020
    networks:
      - rapido

  rapido.customers:
    build:
      context: ../
      dockerfile: src/Services/Customers/Rapido.Services.Customers.Api/Dockerfile
    container_name: customers-service
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ASPNETCORE_HTTP_PORTS: 5030
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://rapido.jaeger:4317"
    ports:
      - 5020
    networks:
      - rapido

  rapido.currencies:
    build:
      context: ../
      dockerfile: src/Services/Currencies/Rapido.Services.Currencies.Api/Dockerfile
    container_name: currencies-service
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ASPNETCORE_HTTP_PORTS: 5060
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://rapido.jaeger:4317"
    ports:
      - 5060
    networks:
      - rapido

  rapido.wallets:
    build:
      context: ../
      dockerfile: src/Services/Wallets/Rapido.Services.Wallets.Api/Dockerfile
    container_name: wallets-service
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ASPNETCORE_HTTP_PORTS: 5040
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://rapido.jaeger:4317"
    ports:
      - 5040
    networks:
      - rapido

  rapido.payments:
    build:
      context: ../
      dockerfile: src/Services/Payments/Rapido.Services.Payments.Api/Dockerfile
    container_name: payments-service
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ASPNETCORE_HTTP_PORTS: 5050
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://rapido.jaeger:4317"
    ports:
      - 5050
    networks:
      - rapido

  rapido.notifications:
    build:
      context: ../
      dockerfile: src/Services/Notifications/Rapido.Services.Notifications.Api/Dockerfile
    container_name: notifications-service
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ASPNETCORE_HTTP_PORTS: 5090
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://rapido.jaeger:4317"
    ports:
      - 5090
    networks:
      - rapido

networks:
  rapido:
    name: rapido
    external: true